name: Wake Up Dashboard

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Full Page Request
        run: |
          # Added -A (User Agent) and -f (fail silently but return error code)
          curl -I -L -s -A "Mozilla/5.0" https://ng-health-dashboard.streamlit.app/
          echo "Knocked on the door at $(date)"